-- Create storage for one-time password reset tokens.
--
-- Run manually after review:
--
--   psql dogn -f scripts/add_password_reset_tokens.sql
--
-- This migration changes schema only. It does not modify existing users,
-- passwords, or sessions.

BEGIN;

CREATE TABLE IF NOT EXISTS password_reset_token (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES user_info(id) ON DELETE CASCADE,
    token_hash text NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamp NOT NULL,
    used_at timestamp,
    request_ip text
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_password_reset_token_hash
    ON password_reset_token(token_hash);

CREATE INDEX IF NOT EXISTS idx_password_reset_token_user_id
    ON password_reset_token(user_id);

CREATE INDEX IF NOT EXISTS idx_password_reset_token_active
    ON password_reset_token(expires_at)
    WHERE used_at IS NULL;

COMMENT ON TABLE password_reset_token IS
    'One-time password reset token hashes; raw reset tokens are never stored';

COMMENT ON COLUMN password_reset_token.user_id IS
    'User account that requested the password reset';

COMMENT ON COLUMN password_reset_token.token_hash IS
    'Hash of the raw reset token sent by email';

COMMENT ON COLUMN password_reset_token.expires_at IS
    'Time after which the reset token is invalid';

COMMENT ON COLUMN password_reset_token.used_at IS
    'Time the token was consumed; NULL means unused';

COMMENT ON COLUMN password_reset_token.request_ip IS
    'Optional requester IP address for audit or throttling';

COMMIT;
