\set ON_ERROR_STOP on

-- Initialize an empty dogn database with the current application schema and
-- one administrator account.
--
-- This script creates schema objects and inserts only one user_info row:
--   id=1, name='admin', level=10, password_scheme='argon2id-v1'
--
-- The password hash is intentionally not stored in this file. Generate an
-- Argon2id hash with trusted tooling and pass it as a psql variable:
--
--   psql dogn_sample \
--     -v admin_password_hash='$argon2id$...' \
--     -v ON_ERROR_STOP=1 \
--     -f scripts/dogn_sample.sql
--
-- Prerequisite: PGroonga must be installed in PostgreSQL before this script is
-- run, because the application search indexes use the pgroonga access method.

\if :{?admin_password_hash}
\else
\echo 'ERROR: admin_password_hash is required.'
\echo 'Usage: psql dogn_sample -v admin_password_hash=''$argon2id$...'' -v ON_ERROR_STOP=1 -f scripts/dogn_sample.sql'
\quit 1
\endif

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgroonga;

CREATE TABLE category (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character(10) NOT NULL DEFAULT '',
    comment character(25),
    order_id integer NOT NULL DEFAULT 0,
    board_count integer NOT NULL DEFAULT 0
);

CREATE TABLE board (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character(10) NOT NULL DEFAULT '',
    comment character(25),
    category_id integer NOT NULL DEFAULT 0,
    post_count integer NOT NULL DEFAULT 0,
    root_count integer,
    master_id integer NOT NULL DEFAULT 0,
    order_id integer NOT NULL DEFAULT 0
);

CREATE TABLE user_info (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character(25) NOT NULL DEFAULT '',
    password text NOT NULL DEFAULT '',
    state integer NOT NULL DEFAULT 0,
    level integer NOT NULL DEFAULT 0,
    email character(25),
    intro character(100),
    reg_time timestamp without time zone,
    post_count integer NOT NULL DEFAULT 0,
    doc_count integer NOT NULL DEFAULT 0,
    last_login timestamp without time zone,
    last_login_ip character(15),
    last_origin timestamp without time zone,
    last_reship timestamp without time zone,
    last_post timestamp without time zone,
    login_count integer NOT NULL DEFAULT 0,
    point integer,
    intro_user_id integer,
    sign_id integer,
    favorite_count integer NOT NULL DEFAULT 0,
    log_error_time timestamp without time zone,
    log_error_count integer NOT NULL DEFAULT 0,
    password_scheme text
);

CREATE TABLE post (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id integer,
    parent_id integer,
    root_id integer,
    order_num integer NOT NULL DEFAULT 0,
    order_num_2 integer DEFAULT 10000,
    level integer NOT NULL DEFAULT 0,
    subject character varying(100),
    size integer,
    access_count integer NOT NULL DEFAULT 0,
    user_name character varying(25),
    user_id integer,
    post_time timestamp without time zone,
    reply_count integer DEFAULT 0,
    reply_time timestamp without time zone,
    type integer,
    content text,
    link_name character varying(25),
    link_url character varying(100),
    image_url character varying(100),
    state integer NOT NULL DEFAULT 0,
    folder_id integer DEFAULT 0,
    point integer DEFAULT 0,
    sign_id integer NOT NULL DEFAULT 0,
    last_update_time timestamp without time zone,
    content_format smallint NOT NULL DEFAULT 0,
    CONSTRAINT post_content_format_check CHECK (content_format IN (0, 1))
);

CREATE TABLE board_master (
    board_id integer NOT NULL REFERENCES board(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES user_info(id) ON DELETE RESTRICT,
    order_id integer NOT NULL DEFAULT 0,
    CONSTRAINT board_master_pkey PRIMARY KEY (board_id, user_id)
);

CREATE TABLE favorite (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL DEFAULT 0,
    post_id integer NOT NULL DEFAULT 0,
    create_time timestamp without time zone
);

CREATE TABLE point_log (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id integer,
    user_id integer,
    point integer,
    post_time timestamp without time zone
);

CREATE TABLE sign_log (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL DEFAULT 0,
    sign_id integer NOT NULL DEFAULT 0,
    set_time timestamp without time zone
);

CREATE TABLE password_reset_token (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES user_info(id) ON DELETE CASCADE,
    token_hash text NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamp without time zone NOT NULL,
    used_at timestamp without time zone,
    request_ip text
);

CREATE INDEX idx_board_category_id ON board (category_id);
CREATE INDEX idx_board_category_order ON board (category_id, order_id, id);

CREATE INDEX idx_board_master_board_order ON board_master (board_id, order_id, user_id);
CREATE INDEX idx_board_master_user_id ON board_master (user_id);

CREATE INDEX idx_category_order ON category (order_id, id);

CREATE INDEX idx_favorite_create_time ON favorite (create_time);
CREATE INDEX idx_favorite_post_id ON favorite (post_id);
CREATE INDEX idx_favorite_user_id ON favorite (user_id);
CREATE INDEX idx_favorite_user_id_desc ON favorite (user_id, id DESC);
CREATE INDEX idx_favorite_user_post ON favorite (user_id, post_id);

CREATE UNIQUE INDEX idx_password_reset_token_hash ON password_reset_token (token_hash);
CREATE INDEX idx_password_reset_token_user_id ON password_reset_token (user_id);
CREATE INDEX idx_password_reset_token_active
    ON password_reset_token (expires_at)
    WHERE used_at IS NULL;

CREATE INDEX idx_point_log_post_time ON point_log (post_time);
CREATE INDEX idx_point_log_post_time_id ON point_log (post_id, post_time, id);

CREATE INDEX idx_post_board_id ON post (board_id);
CREATE INDEX idx_post_effective_root_all ON post ((COALESCE(root_id, id)));
CREATE INDEX idx_post_parent_id ON post (parent_id);
CREATE INDEX idx_post_post_time_access_count ON post (post_time, access_count);
CREATE INDEX idx_post_search_content_pgroonga
    ON post USING pgroonga ((COALESCE(content, '')::text))
    WHERE state IN (0, 1);
CREATE INDEX idx_post_search_has_image
    ON post (id)
    WHERE state IN (0, 1)
      AND NULLIF(BTRIM(image_url), '') IS NOT NULL;
CREATE INDEX idx_post_search_has_link
    ON post (id)
    WHERE state IN (0, 1)
      AND NULLIF(BTRIM(link_url), '') IS NOT NULL;
CREATE INDEX idx_post_search_post_time
    ON post (post_time)
    WHERE state IN (0, 1);
CREATE INDEX idx_post_search_reply_time
    ON post (reply_time)
    WHERE state IN (0, 1);
CREATE INDEX idx_post_search_subject_pgroonga
    ON post USING pgroonga (((COALESCE(subject, ''))::text))
    WHERE state IN (0, 1);
CREATE INDEX idx_post_search_type
    ON post (type)
    WHERE state IN (0, 1);
CREATE INDEX idx_post_search_user_name_pgroonga
    ON post USING pgroonga (((COALESCE(user_name, ''))::text))
    WHERE state IN (0, 1);
CREATE INDEX idx_post_search_visible_id
    ON post (id)
    WHERE state IN (0, 1);
CREATE INDEX idx_post_tree_order_all ON post (root_id, order_num);
CREATE INDEX idx_post_type ON post (type);
CREATE INDEX idx_post_user_id ON post (user_id);
CREATE INDEX idx_post_visible_board_roots
    ON post (board_id, id)
    WHERE state IN (0, 1)
      AND COALESCE(parent_id, 0) = 0;
CREATE INDEX idx_post_visible_board_tree_order
    ON post (board_id, (COALESCE(root_id, id)) DESC, order_num)
    WHERE state IN (0, 1);
CREATE INDEX idx_post_visible_roots_home
    ON post ((COALESCE(root_id, id)) DESC, order_num)
    WHERE state IN (0, 1)
      AND COALESCE(parent_id, 0) = 0;
CREATE INDEX idx_post_visible_tree_order
    ON post ((COALESCE(root_id, id)), order_num)
    WHERE state IN (0, 1);
CREATE INDEX idx_post_visible_tree_post_time
    ON post ((COALESCE(root_id, id)), post_time, id)
    WHERE state IN (0, 1);
CREATE INDEX idx_post_visible_type_id
    ON post (type, id DESC)
    WHERE state IN (0, 1);
CREATE INDEX idx_post_visible_user_post_time
    ON post (user_id, post_time DESC)
    WHERE state IN (0, 1);
CREATE INDEX idx_post_visible_user_type_id
    ON post (user_id, type, id DESC)
    WHERE state IN (0, 1);
CREATE INDEX idx_post_visible_user_type_post_time
    ON post (user_id, type, post_time DESC)
    WHERE state IN (0, 1);

CREATE INDEX idx_sign_log_sign_id ON sign_log (sign_id);
CREATE INDEX idx_sign_log_user_id ON sign_log (user_id);
CREATE INDEX idx_sign_log_user_id_desc ON sign_log (user_id, id DESC);
CREATE INDEX idx_sign_log_user_latest ON sign_log (user_id, set_time DESC NULLS LAST, id DESC);

CREATE INDEX idx_user_info_level_id ON user_info (level, id);
CREATE INDEX idx_user_info_name ON user_info (name);
CREATE INDEX idx_user_info_point ON user_info (point);
CREATE INDEX idx_user_info_point_id ON user_info (point DESC NULLS LAST, id);
CREATE INDEX idx_user_info_reg_time ON user_info (reg_time);
CREATE INDEX idx_user_info_trimmed_email_level
    ON user_info (LOWER(BTRIM(email)), level)
    WHERE NULLIF(BTRIM(email), '') IS NOT NULL;
CREATE INDEX idx_user_info_trimmed_name ON user_info (BTRIM(name));

COMMENT ON COLUMN post.content_format IS
    'Post body format: 0=plain text, 1=Markdown rendered client-side after sanitization.';
COMMENT ON TABLE password_reset_token IS
    'One-time password reset token hashes; raw reset tokens are never stored';
COMMENT ON COLUMN password_reset_token.user_id IS
    'User account that requested the password reset';
COMMENT ON COLUMN password_reset_token.token_hash IS
    'Hash of the raw reset token sent by email';
COMMENT ON COLUMN password_reset_token.expires_at IS
    'Time after which the reset token is invalid';
COMMENT ON COLUMN password_reset_token.used_at IS
    'Time the token was consumed; NULL means unused';
COMMENT ON COLUMN password_reset_token.request_ip IS
    'Optional requester IP address for audit or throttling';

INSERT INTO user_info (
    id,
    name,
    password,
    password_scheme,
    state,
    level,
    reg_time,
    post_count,
    doc_count,
    login_count,
    point,
    favorite_count,
    log_error_count
) VALUES (
    1,
    'admin',
    :'admin_password_hash',
    'argon2id-v1',
    0,
    10,
    CURRENT_TIMESTAMP,
    0,
    0,
    0,
    100,
    0,
    0
);

SELECT setval(pg_get_serial_sequence('user_info', 'id'), 1, true);

COMMIT;
