#!/usr/bin/env bash
set -euo pipefail

# Migrates the local MySQL database "dogn" into the local PostgreSQL database
# "dogn". This script intentionally performs writes only against PostgreSQL.
#
# Usage:
#   chmod +x migrate_mysql_to_postgres.sh
#   ./migrate_mysql_to_postgres.sh --mysql-password 'your-password' --yes
#
# Optional overrides:
#   MYSQL_USER=zqh MYSQL_DATABASE=dogn PGDATABASE=dogn ./migrate_mysql_to_postgres.sh --mysql-password 'your-password' --yes

MYSQL_USER=${MYSQL_USER:-zqh}
MYSQL_DATABASE=${MYSQL_DATABASE:-dogn}
MYSQL_CMD=${MYSQL_CMD:-"mysql -u ${MYSQL_USER} --default-character-set=utf8mb4 ${MYSQL_DATABASE}"}
PGDATABASE=${PGDATABASE:-dogn}
PSQL_CMD=${PSQL_CMD:-"psql -v ON_ERROR_STOP=1 -d ${PGDATABASE}"}
MYSQL_PASSWORD=${MYSQL_PWD:-}
confirmed=0

usage() {
  cat >&2 <<EOF
Usage:
  $0 --mysql-password PASSWORD --yes

This will DROP and recreate the migrated tables in PostgreSQL database "${PGDATABASE}".
It will read from MySQL database "${MYSQL_DATABASE}" as MySQL user "${MYSQL_USER}" and will not write to MySQL.

Options:
  --mysql-password, -p PASSWORD  MySQL password. You can also set MYSQL_PWD instead.
  --yes                         Confirm the PostgreSQL destructive migration.
  --help                        Show this help text.

Optional environment overrides:
  MYSQL_USER=zqh
  MYSQL_DATABASE=dogn
  PGDATABASE=dogn
  MYSQL_CMD='mysql -u zqh --default-character-set=utf8mb4 dogn'
  PSQL_CMD='psql -v ON_ERROR_STOP=1 -d dogn'
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mysql-password|-p)
      if [[ $# -lt 2 ]]; then
        echo "Missing value for $1" >&2
        usage
        exit 2
      fi
      MYSQL_PASSWORD=$2
      shift 2
      ;;
    --yes)
      confirmed=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 2
      ;;
  esac
done

if [[ "$confirmed" != "1" ]]; then
  usage
  echo >&2
  echo "Run with --yes to continue." >&2
  exit 2
fi

if [[ -z "$MYSQL_PASSWORD" ]]; then
  usage
  echo >&2
  echo "Missing MySQL password. Pass --mysql-password PASSWORD or set MYSQL_PWD." >&2
  exit 2
fi

for bin in mysql psql python3; do
  if ! command -v "$bin" >/dev/null 2>&1; then
    echo "Missing required command: $bin" >&2
    exit 1
  fi
done

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

run_psql() {
  $PSQL_CMD "$@"
}

run_mysql() {
  # --raw keeps MySQL JSON output parseable by the Python CSV bridge below.
  MYSQL_PWD=$MYSQL_PASSWORD $MYSQL_CMD --batch --raw --skip-column-names "$@"
}

dt_expr() {
  local col=$1
  printf "NULLIF(DATE_FORMAT(%s, '%%Y-%%m-%%d %%H:%%i:%%s'), '0000-00-00 00:00:00')" "$col"
}

json_to_csv() {
  python3 -c '
import json
import sys

nul_fields = 0

def csv_field(value):
    global nul_fields
    if value is None:
        return ""
    text = str(value)
    if "\x00" in text:
        nul_fields += 1
        text = text.replace("\x00", "")
    return "\"" + text.replace("\"", "\"\"") + "\""

for line_no, line in enumerate(sys.stdin, 1):
    line = line.rstrip("\n")
    if not line:
        continue
    try:
        row = json.loads(line)
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Invalid JSON from MySQL on line {line_no}: {exc}") from exc
    sys.stdout.write(",".join(csv_field(value) for value in row) + "\n")

if nul_fields:
    print(f"Warning: stripped PostgreSQL-incompatible NUL bytes from {nul_fields} field(s).", file=sys.stderr)
'
}

copy_table() {
  local table=$1
  local pg_columns=$2
  shift 2

  local query="SET SESSION time_zone = '+00:00'; SELECT JSON_ARRAY("
  local sep=""
  local expr
  for expr in "$@"; do
    query+="${sep}${expr}"
    sep=", "
  done
  query+=") FROM \`${table}\`"

  echo "Loading ${table}..."
  run_mysql -e "$query" |
    json_to_csv |
    run_psql -c "\\copy \"${table}\" (${pg_columns}) FROM STDIN WITH (FORMAT csv, NULL '')"
}

echo "Creating PostgreSQL schema..."
run_psql <<'SQL'
BEGIN;

SET client_encoding = 'UTF8';
SET TIME ZONE 'UTC';

DROP TABLE IF EXISTS "favorite";
DROP TABLE IF EXISTS "point_log";
DROP TABLE IF EXISTS "sign_log";
DROP TABLE IF EXISTS "upd_log";
DROP TABLE IF EXISTS "article";
DROP TABLE IF EXISTS "forum";
DROP TABLE IF EXISTS "category";
DROP TABLE IF EXISTS "info_bak";
DROP TABLE IF EXISTS "user";

CREATE TABLE "article" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ForumId" integer,
  "ParentId" integer,
  "RootId" integer,
  "OrderNum" integer NOT NULL DEFAULT 0,
  "OrderNum2" integer DEFAULT 10000,
  "Level" integer NOT NULL DEFAULT 0,
  "Subject" varchar(100),
  "Size" integer,
  "AccessCount" integer NOT NULL DEFAULT 0,
  "UserName" varchar(25),
  "UserId" integer,
  "PostTime" timestamp,
  "ReplyCount" integer DEFAULT 0,
  "ReplyTime" timestamp,
  "Type" integer,
  "Content" text,
  "LinkName" varchar(25),
  "LinkStr" varchar(100),
  "ImageLink" varchar(100),
  "State" integer NOT NULL DEFAULT 0,
  "FolderId" integer DEFAULT 0,
  "Point" integer DEFAULT 0,
  "SignId" integer NOT NULL DEFAULT 0
);

CREATE TABLE "category" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" char(10) NOT NULL DEFAULT '',
  "Comment" char(25),
  "OrderId" integer NOT NULL DEFAULT 0,
  "ForumCount" integer NOT NULL DEFAULT 0
);

CREATE TABLE "favorite" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" integer NOT NULL DEFAULT 0,
  "ArticleId" integer NOT NULL DEFAULT 0,
  "CreateTime" timestamp
);

CREATE TABLE "forum" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" char(10) NOT NULL DEFAULT '',
  "Comment" char(25),
  "CategoryId" integer NOT NULL DEFAULT 0,
  "ArtCount" integer NOT NULL DEFAULT 0,
  "RootCount" integer,
  "MasterName" char(25),
  "MasterName2" char(25),
  "MasterName3" char(25),
  "MasterName4" char(25),
  "MasterId" integer NOT NULL DEFAULT 0,
  "OrderId" integer NOT NULL DEFAULT 0
);

CREATE TABLE "info_bak" (
  "ID" integer NOT NULL DEFAULT 0,
  "name" char(25) NOT NULL DEFAULT '',
  "password" char(32),
  "state" integer NOT NULL DEFAULT 0,
  "usrlevel" integer NOT NULL DEFAULT 0,
  "Email" char(25),
  "intro" char(100),
  "regtime" timestamp,
  "artcount" integer NOT NULL DEFAULT 0,
  "doccount" integer NOT NULL DEFAULT 0,
  "lastlogin" timestamp,
  "lastloginip" char(15),
  "lastOrigin" timestamp,
  "lastReship" timestamp,
  "lastPost" timestamp,
  "logincount" integer NOT NULL DEFAULT 0,
  "points" integer,
  "introuser" integer,
  "signatureid" integer,
  "FavoCount" integer NOT NULL DEFAULT 0,
  "logerrtime" timestamp,
  "logerrcount" integer NOT NULL DEFAULT 0
);

CREATE TABLE "point_log" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ArticleId" integer,
  "UserId" integer,
  "Point" integer,
  "PostTime" timestamp
);

CREATE TABLE "sign_log" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" integer NOT NULL DEFAULT 0,
  "SignId" integer NOT NULL DEFAULT 0,
  "SetTime" timestamp
);

CREATE TABLE "upd_log" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "query" varchar(4096),
  "file" varchar(30),
  "time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "user" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" char(25) NOT NULL DEFAULT '',
  "Password" char(32) NOT NULL DEFAULT '',
  "State" integer NOT NULL DEFAULT 0,
  "Level" integer NOT NULL DEFAULT 0,
  "Email" char(25),
  "Intro" char(100),
  "RegTime" timestamp,
  "ArticleCount" integer NOT NULL DEFAULT 0,
  "DocCount" integer NOT NULL DEFAULT 0,
  "LastLogin" timestamp,
  "LastLoginIp" char(15),
  "LastOrigin" timestamp,
  "LastReship" timestamp,
  "LastPost" timestamp,
  "LoginCount" integer NOT NULL DEFAULT 0,
  "Point" integer,
  "IntroUserId" integer,
  "SignId" integer,
  "FavoCount" integer NOT NULL DEFAULT 0,
  "LogErrTime" timestamp,
  "LogErrCount" integer NOT NULL DEFAULT 0
);

COMMIT;
SQL

copy_table "category" '"Id","Name","Comment","OrderId","ForumCount"' \
  '`Id`' '`Name`' '`Comment`' '`OrderId`' '`ForumCount`'

copy_table "forum" '"Id","Name","Comment","CategoryId","ArtCount","RootCount","MasterName","MasterName2","MasterName3","MasterName4","MasterId","OrderId"' \
  '`Id`' '`Name`' '`Comment`' '`CategoryId`' '`ArtCount`' '`RootCount`' '`MasterName`' '`MasterName2`' '`MasterName3`' '`MasterName4`' '`MasterId`' '`OrderId`'

copy_table "user" '"Id","Name","Password","State","Level","Email","Intro","RegTime","ArticleCount","DocCount","LastLogin","LastLoginIp","LastOrigin","LastReship","LastPost","LoginCount","Point","IntroUserId","SignId","FavoCount","LogErrTime","LogErrCount"' \
  '`Id`' '`Name`' '`Password`' '`State`' '`Level`' '`Email`' '`Intro`' "$(dt_expr '`RegTime`')" '`ArticleCount`' '`DocCount`' "$(dt_expr '`LastLogin`')" '`LastLoginIp`' "$(dt_expr '`LastOrigin`')" "$(dt_expr '`LastReship`')" "$(dt_expr '`LastPost`')" '`LoginCount`' '`Point`' '`IntroUserId`' '`SignId`' '`FavoCount`' "$(dt_expr '`LogErrTime`')" '`LogErrCount`'

copy_table "article" '"Id","ForumId","ParentId","RootId","OrderNum","OrderNum2","Level","Subject","Size","AccessCount","UserName","UserId","PostTime","ReplyCount","ReplyTime","Type","Content","LinkName","LinkStr","ImageLink","State","FolderId","Point","SignId"' \
  '`Id`' '`ForumId`' '`ParentId`' '`RootId`' '`OrderNum`' '`OrderNum2`' '`Level`' '`Subject`' '`Size`' '`AccessCount`' '`UserName`' '`UserId`' "$(dt_expr '`PostTime`')" '`ReplyCount`' "$(dt_expr '`ReplyTime`')" '`Type`' '`Content`' '`LinkName`' '`LinkStr`' '`ImageLink`' '`State`' '`FolderId`' '`Point`' '`SignId`'

copy_table "favorite" '"Id","UserId","ArticleId","CreateTime"' \
  '`Id`' '`UserId`' '`ArticleId`' "$(dt_expr '`CreateTime`')"

copy_table "info_bak" '"ID","name","password","state","usrlevel","Email","intro","regtime","artcount","doccount","lastlogin","lastloginip","lastOrigin","lastReship","lastPost","logincount","points","introuser","signatureid","FavoCount","logerrtime","logerrcount"' \
  '`ID`' '`name`' '`password`' '`state`' '`usrlevel`' '`Email`' '`intro`' "$(dt_expr '`regtime`')" '`artcount`' '`doccount`' "$(dt_expr '`lastlogin`')" '`lastloginip`' "$(dt_expr '`lastOrigin`')" "$(dt_expr '`lastReship`')" "$(dt_expr '`lastPost`')" '`logincount`' '`points`' '`introuser`' '`signatureid`' '`FavoCount`' "$(dt_expr '`logerrtime`')" '`logerrcount`'

copy_table "point_log" '"Id","ArticleId","UserId","Point","PostTime"' \
  '`Id`' '`ArticleId`' '`UserId`' '`Point`' "$(dt_expr '`PostTime`')"

copy_table "sign_log" '"Id","UserId","SignId","SetTime"' \
  '`Id`' '`UserId`' '`SignId`' "$(dt_expr '`SetTime`')"

copy_table "upd_log" '"id","query","file","time"' \
  '`id`' '`query`' '`file`' "$(dt_expr '`time`')"

echo "Creating indexes and resetting identity sequences..."
run_psql <<'SQL'
BEGIN;

CREATE INDEX "IdxForumId" ON "article" ("ForumId");
CREATE INDEX "IdxParentId" ON "article" ("ParentId");
CREATE INDEX "IdxAccessCount" ON "article" ("AccessCount");
CREATE INDEX "IdxPoint_article" ON "article" ("Point");
CREATE INDEX "IdxType" ON "article" ("Type");
CREATE INDEX "IdxUserId_article" ON "article" ("UserId");
CREATE INDEX "IdxTreeOrder" ON "article" ("RootId", "OrderNum2");
CREATE INDEX "IdxPostTimeAccessCount" ON "article" ("PostTime", "AccessCount");

CREATE INDEX "IdxUserId_favorite" ON "favorite" ("UserId");
CREATE INDEX "IdxArticleId" ON "favorite" ("ArticleId");
CREATE INDEX "IdxCreateTime" ON "favorite" ("CreateTime");

CREATE INDEX "IdxCategoryId" ON "forum" ("CategoryId");

CREATE INDEX "IdxPostTime" ON "point_log" ("PostTime");

CREATE INDEX "IDX_USERID" ON "sign_log" ("UserId");
CREATE INDEX "IDX_SETTIME" ON "sign_log" ("SetTime");

CREATE INDEX "IdxPoint_user" ON "user" ("Point");
CREATE INDEX "IdxName" ON "user" ("Name");
CREATE INDEX "IdxRegTime" ON "user" ("RegTime");

SELECT setval(pg_get_serial_sequence('"article"', 'Id'), COALESCE(MAX("Id"), 1), MAX("Id") IS NOT NULL) FROM "article";
SELECT setval(pg_get_serial_sequence('"category"', 'Id'), COALESCE(MAX("Id"), 1), MAX("Id") IS NOT NULL) FROM "category";
SELECT setval(pg_get_serial_sequence('"favorite"', 'Id'), COALESCE(MAX("Id"), 1), MAX("Id") IS NOT NULL) FROM "favorite";
SELECT setval(pg_get_serial_sequence('"forum"', 'Id'), COALESCE(MAX("Id"), 1), MAX("Id") IS NOT NULL) FROM "forum";
SELECT setval(pg_get_serial_sequence('"point_log"', 'Id'), COALESCE(MAX("Id"), 1), MAX("Id") IS NOT NULL) FROM "point_log";
SELECT setval(pg_get_serial_sequence('"sign_log"', 'Id'), COALESCE(MAX("Id"), 1), MAX("Id") IS NOT NULL) FROM "sign_log";
SELECT setval(pg_get_serial_sequence('"upd_log"', 'id'), COALESCE(MAX("id"), 1), MAX("id") IS NOT NULL) FROM "upd_log";
SELECT setval(pg_get_serial_sequence('"user"', 'Id'), COALESCE(MAX("Id"), 1), MAX("Id") IS NOT NULL) FROM "user";

COMMIT;
SQL

echo "Verifying row counts..."
{
  echo "table,mysql_count,postgres_count"
  for table in article category favorite forum info_bak point_log sign_log upd_log user; do
    mysql_count=$(run_mysql -e "SELECT COUNT(*) FROM \`${table}\`")
    pg_count=$(run_psql -At -c "SELECT COUNT(*) FROM \"${table}\"")
    echo "${table},${mysql_count},${pg_count}"
    if [[ "$mysql_count" != "$pg_count" ]]; then
      echo "Row count mismatch for ${table}: MySQL=${mysql_count}, PostgreSQL=${pg_count}" >&2
      exit 1
    fi
  done
} | tee "$tmpdir/row_counts.csv"

echo "Migration completed successfully."
