CREATE TABLE category (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    comment text,
    order_id integer NOT NULL DEFAULT 0,
    board_count integer
);

CREATE TABLE board (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    comment text,
    category_id integer NOT NULL REFERENCES category(id),
    post_count integer NOT NULL DEFAULT 0,
    root_count integer,
    order_id integer NOT NULL DEFAULT 0
);

CREATE TABLE post (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject text,
    board_id integer REFERENCES board(id),
    user_id integer,
    user_name text,
    post_time timestamp,
    reply_time timestamp,
    last_update_time timestamp,
    size integer,
    reply_count integer,
    access_count integer NOT NULL DEFAULT 0,
    point integer,
    type integer,
    state integer NOT NULL DEFAULT 0,
    content text,
    link_name text,
    link_url text,
    image_url text,
    sign_id integer,
    parent_id integer,
    root_id integer,
    level integer NOT NULL DEFAULT 0,
    order_num integer
);

CREATE TABLE user_info (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    password text NOT NULL,
    password_scheme text,
    state integer NOT NULL DEFAULT 0,
    level integer NOT NULL DEFAULT 1,
    email text,
    reg_time timestamp,
    post_count integer NOT NULL DEFAULT 0,
    doc_count integer,
    last_login timestamp,
    last_login_ip text,
    last_origin timestamp,
    last_reship timestamp,
    last_post timestamp,
    login_count integer,
    intro_user_id integer,
    point integer,
    intro text,
    favorite_count integer,
    log_error_time timestamp,
    log_error_count integer NOT NULL DEFAULT 0
);

CREATE TABLE board_master (
    board_id integer NOT NULL REFERENCES board(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES user_info(id) ON DELETE RESTRICT,
    order_id integer NOT NULL DEFAULT 0,
    PRIMARY KEY (board_id, user_id)
);

CREATE INDEX idx_board_master_user_id ON board_master(user_id);

CREATE TABLE point_log (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id integer NOT NULL REFERENCES post(id),
    user_id integer NOT NULL REFERENCES user_info(id),
    point integer NOT NULL,
    post_time timestamp
);

CREATE TABLE favorite (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES user_info(id),
    post_id integer NOT NULL REFERENCES post(id),
    create_time timestamp
);

CREATE TABLE sign_log (
    id integer PRIMARY KEY,
    user_id integer NOT NULL REFERENCES user_info(id),
    sign_id integer NOT NULL REFERENCES post(id),
    set_time timestamp
);

CREATE TABLE password_reset_token (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES user_info(id) ON DELETE CASCADE,
    token_hash text NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamp NOT NULL,
    used_at timestamp,
    request_ip text
);

CREATE UNIQUE INDEX idx_password_reset_token_hash
    ON password_reset_token(token_hash);

CREATE INDEX idx_password_reset_token_user_id
    ON password_reset_token(user_id);

CREATE INDEX idx_password_reset_token_active
    ON password_reset_token(expires_at)
    WHERE used_at IS NULL;
